name = "apigw"
account_id = "f5686db3c4f5b3e38b8f15b0561a28a8"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

routes = [
    { pattern = "apigw.eragon.xyz", custom_domain = true }, # deploying on a separate zone to allow using CF Access on upstream
]
