name = "rentwatch"
main = "src/index.ts"
compatibility_date = "2022-09-06"
account_id = "f5686db3c4f5b3e38b8f15b0561a28a8"

routes = [
	{ pattern = "rentwatch.mirio.dev", custom_domain = true }
]


[[r2_buckets]]
binding = "RENTWATCH_BUCKET"
bucket_name = "rentwatch-mirio-dev"
preview_bucket_name = "rentwatch-mirio-dev-preview"

[triggers]
crons = ["0 18 * * *"] # Everyday at 11 AM PST
