packages:
  - workers/*
  - packages/*

catalog:
  "wrangler": "^4.80.0"
  "@cloudflare/vitest-pool-workers": "^0.14.1"
  "@cloudflare/workers-types": "^4.20260405.1"
  "vitest": "~3.2.4"
  "turbo": "^2.9.4"
  "typescript": "^6.0.2"
