packages:
  - workers/*
  - packages/*

catalog:
  "wrangler": "^4.78.0"
  "@cloudflare/vitest-pool-workers": "^0.13.5"
  "@cloudflare/workers-types": "^4.20260329.1"
  "vitest": "~3.2.4"
  "turbo": "^2.9.1"
  "typescript": "^6.0.2"
