packages:
  - workers/*
  - packages/*

catalog:
  "wrangler": "^4.61.1"
  "@cloudflare/vitest-pool-workers": "^0.12.8"
  "@cloudflare/workers-types": "^4.20260131.0"
  "vitest": "~4.0.18"
  "turbo": "^2.8.1"
  "typescript": "^5.9.3"
