packages:
  - workers/*
  - packages/*

catalog:
  "wrangler": "^4.82.2"
  "@cloudflare/vitest-pool-workers": "^0.14.6"
  "@cloudflare/workers-types": "^4.20260414.1"
  "vitest": "~3.2.4"
  "turbo": "^2.9.6"
  "typescript": "^6.0.2"
