packages:
  - workers/*
  - packages/*

catalog:
  "wrangler": "^4.60.0"
  "@cloudflare/vitest-pool-workers": "^0.12.6"
  "@cloudflare/workers-types": "^4.20250826.0"
  "vitest": "~3.2.4"
  "turbo": "^2.4.4"
  "typescript": "^5.9.2"
