packages:
  - workers/*
  - packages/*

catalog:
  "wrangler": "^4.33.0"
  "@cloudflare/vitest-pool-workers": "^0.8.67"
  "@cloudflare/workers-types": "^4.20250826.0"
  "vitest": "3.2.4"
  "turbo": "^2.4.4"
  "typescript": "^5.9.2"
