name = "tfstate"
account_id = "f5686db3c4f5b3e38b8f15b0561a28a8"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

routes = [{ pattern = "tfstate.mirio.dev", custom_domain = true }]

r2_buckets = [
    { binding = "TFSTATE_BUCKET", bucket_name = "tfstate-mirio-dev", preview_bucket_name = "tfstate-mirio-dev-preview" },
]

[durable_objects]
bindings = [{ name = "TFSTATE_LOCK", class_name = "DurableLock" }]

[[migrations]]
tag = "v1"
new_classes = ["DurableLock"]

[build]
command = "npm run build"
